apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tlil
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-tlil@sha256:68fd6b69066db9475fd9c4b48cf41941c61ffbec3a2e2b8f0e298e2b75e8696d
        name: my-nodejs
        resources: {}
status: {}
